project:
  type: website
  render:
    - index.qmd
    - chapters/chapter1.qmd

website:
  page-navigation: true
  title: "Educational resource template for Python"
  repo-actions: [edit, source, issue]
  sidebar:
    search: true
    contents:
      - href: index.qmd
        text: Introduction
      - href: chapters/chapter1.qmd
        text: A complete example

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: true
  # Uncomment the following lines if you want Jupyter notebooks as output
  # ipynb: 
  # # Set this to true if you want Jupyter notebooks to contain the output of cells
  #   output: false


filters:
  - export-metadata.lua

